import { saveAs } from 'file-saver';
import * as XLSX from 'xlsx';
import type { Student, AttendanceStatus, AttendanceSummary } from '@shared/types';
import { format } from 'date-fns';

interface AttendanceRecord {
  student: Student;
  status: AttendanceStatus;
}

interface ShareData {
  className: string;
  subject: string;
  teacher: string;
  date: string;
  records: AttendanceRecord[];
  summary: AttendanceSummary;
}

// Generate professional text summary
export function generateTextSummary(data: ShareData): string {
  const lines: string[] = [];

  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━');
  lines.push(`📋 ATTENDANCE REPORT`);
  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━');
  lines.push('');
  lines.push(`🏫 Class: ${data.className}`);
  lines.push(`📚 Subject: ${data.subject}`);
  lines.push(`👨‍🏫 Teacher: ${data.teacher}`);
  lines.push(`📅 Date: ${format(new Date(data.date), 'EEEE, MMMM d, yyyy')}`);
  lines.push('');
  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━');
  lines.push(`✅ Present: ${data.summary.present}`);
  lines.push(`❌ Absent: ${data.summary.absent}`);
  lines.push(`🟡 Leave: ${data.summary.leave}`);
  lines.push(`👥 Total: ${data.summary.total_students}`);
  lines.push(`📊 Percentage: ${data.summary.percentage}%`);
  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━');
  lines.push('');

  const presentStudents = data.records
    .filter((r) => r.status === 'present')
    .map((r) => r.student.full_name);
  const absentStudents = data.records
    .filter((r) => r.status === 'absent')
    .map((r) => r.student.full_name);
  const leaveStudents = data.records
    .filter((r) => r.status === 'leave')
    .map((r) => r.student.full_name);

  if (presentStudents.length > 0) {
    lines.push(`✅ Present (${presentStudents.length}):`);
    lines.push(presentStudents.map((n, i) => `${i + 1}. ${n}`).join('\n'));
    lines.push('');
  }

  if (absentStudents.length > 0) {
    lines.push(`❌ Absent (${absentStudents.length}):`);
    lines.push(absentStudents.map((n, i) => `${i + 1}. ${n}`).join('\n'));
    lines.push('');
  }

  if (leaveStudents.length > 0) {
    lines.push(`🟡 On Leave (${leaveStudents.length}):`);
    lines.push(leaveStudents.map((n, i) => `${i + 1}. ${n}`).join('\n'));
    lines.push('');
  }

  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━');
  lines.push('Generated by ClassAttend 📱');

  return lines.join('\n');
}

// Copy text to clipboard
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    // Fallback
    const textarea = document.createElement('textarea');
    textarea.value = text;
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand('copy');
    document.body.removeChild(textarea);
    return true;
  }
}

// Share via Web Share API or fallback
export async function shareNative(title: string, text: string): Promise<boolean> {
  if (navigator.share) {
    try {
      await navigator.share({ title, text });
      return true;
    } catch {
      return false;
    }
  }
  return copyToClipboard(text);
}

// Open WhatsApp with pre-filled message
export function shareViaWhatsApp(text: string): void {
  const encoded = encodeURIComponent(text);
  window.open(`https://wa.me/?text=${encoded}`, '_blank');
}

// Open email client
export function shareViaEmail(subject: string, body: string): void {
  const encodedSubject = encodeURIComponent(subject);
  const encodedBody = encodeURIComponent(body);
  window.open(`mailto:?subject=${encodedSubject}&body=${encodedBody}`, '_blank');
}

// Open Telegram share
export function shareViaTelegram(text: string): void {
  const encoded = encodeURIComponent(text);
  window.open(`https://t.me/share/url?text=${encoded}`, '_blank');
}

// Export to Excel
export function exportToExcel(data: ShareData, filename: string = 'attendance'): void {
  interface ExcelRow {
    'Roll Number': string;
    'Student Name': string;
    'Gender': string;
    'Status': string;
  }

  const rows: ExcelRow[] = data.records.map((r) => ({
    'Roll Number': r.student.roll_number,
    'Student Name': r.student.full_name,
    'Gender': r.student.gender,
    'Status': r.status.charAt(0).toUpperCase() + r.status.slice(1),
  }));

  // Add summary header
  rows.push({
    'Roll Number': '',
    'Student Name': '--- SUMMARY ---',
    'Gender': '',
    'Status': '',
  });
  rows.push({
    'Roll Number': '',
    'Student Name': `Present: ${data.summary.present}`,
    'Gender': '',
    'Status': '',
  });
  rows.push({
    'Roll Number': '',
    'Student Name': `Absent: ${data.summary.absent}`,
    'Gender': '',
    'Status': '',
  });
  rows.push({
    'Roll Number': '',
    'Student Name': `Leave: ${data.summary.leave}`,
    'Gender': '',
    'Status': '',
  });

  const ws = XLSX.utils.json_to_sheet(rows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Attendance');

  const excelBuffer = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  const blob = new Blob([excelBuffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  saveAs(blob, `${filename}.xlsx`);
}

// Export to CSV
export function exportToCSV(data: ShareData, filename: string = 'attendance'): void {
  const headers = ['Roll Number', 'Student Name', 'Gender', 'Status'];
  const rows = data.records.map((r) => [
    r.student.roll_number,
    r.student.full_name,
    r.student.gender,
    r.status,
  ]);

  const csvContent = [headers, ...rows].map((row) => row.join(',')).join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  saveAs(blob, `${filename}.csv`);
}

// Export to PDF (basic text-based)
export async function exportToPDF(data: ShareData, filename: string = 'attendance'): Promise<void> {
  const { jsPDF } = await import('jspdf');
  const { default: autoTable } = await import('jspdf-autotable');

  const doc = new jsPDF();

  // Header
  doc.setFontSize(18);
  doc.text('Attendance Report', 14, 22);

  doc.setFontSize(11);
  doc.text(`Class: ${data.className}`, 14, 32);
  doc.text(`Subject: ${data.subject}`, 14, 38);
  doc.text(`Teacher: ${data.teacher}`, 14, 44);
  doc.text(`Date: ${format(new Date(data.date), 'MMMM d, yyyy')}`, 14, 50);

  // Summary
  doc.setFontSize(12);
  doc.text(`Present: ${data.summary.present} | Absent: ${data.summary.absent} | Leave: ${data.summary.leave} | Total: ${data.summary.total_students} | Percentage: ${data.summary.percentage}%`, 14, 60);

  // Table
  const tableData = data.records.map((r) => [
    r.student.roll_number,
    r.student.full_name,
    String(r.student.gender),
    r.status.charAt(0).toUpperCase() + r.status.slice(1),
  ]);

  autoTable(doc, {
    startY: 68,
    head: [['Roll No.', 'Name', 'Gender', 'Status']],
    body: tableData,
    styles: { fontSize: 9 },
    headStyles: { fillColor: [99, 102, 241] },
  });

  doc.save(`${filename}.pdf`);
}
